# Generated by Django 3.2.9 on 2021-12-13 18:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RawMaterials',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('RMCode', models.CharField(help_text='RM01', max_length=20, unique=True)),
                ('Material', models.CharField(max_length=20, unique=True)),
                ('Units', models.CharField(max_length=20)),
                ('Types', models.CharField(choices=[('Leather', 'Leather'), ('Paint', 'Paint'), ('Iron', 'Iron'), ('Plastic', 'Plastic')], default='Accounts', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='RMDemand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('DNo', models.CharField(help_text='DN01', max_length=20, unique=True)),
                ('Date', models.DateField()),
                ('PlanNo', models.CharField(help_text='PLN01', max_length=20, unique=True)),
                ('CancelledDates', models.DateField()),
                ('PONo', models.CharField(help_text='PON01', max_length=20, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='DemandedMaterials',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('DemandedQuantity', models.CharField(max_length=200)),
                ('CurrentStock', models.CharField(max_length=200)),
                ('status', models.CharField(max_length=200)),
                ('Priority', models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4')], default='1', max_length=50)),
                ('DNo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.rmdemand', to_field='DNo')),
                ('RMCode', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.rawmaterials', to_field='RMCode')),
            ],
        ),
    ]
