# Generated by Django 3.2.7 on 2021-12-30 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_alter_demandedmaterials_dno'),
    ]

    operations = [
        migrations.AlterField(
            model_name='demandedmaterials',
            name='DNo',
            field=models.IntegerField(max_length=200),
        ),
        migrations.AlterField(
            model_name='rmdemand',
            name='DNo',
            field=models.IntegerField(help_text='01', max_length=20, unique=True),
        ),
    ]
